### ISSUE TITLE
React.Spread has been deprecated in react 15 and newer

### ISSUE THREAD

**Issue by bsthomsen** [chenglou/react-spinner#15]
https://github.com/chenglou/react-spinner/blob/master/index.js#L21

Throws a warning:
> Warning: React.__spread is deprecated and should not be used. Use Object.assign directly or another helper function with similar semantics. You may be seeing this warning due to your compiler. See https://fb.me/react-spread-deprecation for more details.

They suggest that people use babel-loader instead of react-tools.

**Comment by thebuilder** [comment]
Guess it's the compiled version that fails. Looking at index.jsx it's using {... props}, but it's been compiled to React.__spread.

**Comment by bsthomsen** [comment]
Yea an easy fix would be to change the precompiler to babel-loader. But where would this be changed in the Statics branch?

**Comment by chenglou** [comment]
Thanks! Published as v0.2.6

**Comment by chenglou** [comment]
I've just upgraded this from the good old jsx CLI tool to web pack. The amount of changes is a bit too much, heh.

Btw how do you guys require the css dependency from this repo? Curious.

**Comment by bsthomsen** [comment]
Well I would just expect it to be a part of the module, so that the styles are bundled along with webpack.

**Comment by chenglou** [comment]
My worry is that, say you made library A which requires the spinner and reaches into `node_modules/react-spinner/react-spinner.css`, and then someone else requires A, that node_modules path would be wrong under npm3 since it'd exists at that person's project's root, not A's. But I guess nobody requires css like that anymore.

**Comment by bsthomsen** [comment]
I have it like this at the moment, an import in my main.scss:
`@import "../../node_modules/react-spinner/react-spinner.css";`
