### ISSUE TITLE
Deprecation Warning about use of `React.createClass` as of React v15.5.0

### ISSUE THREAD

**Issue by maikthomas** [chenglou/react-spinner#20]
`React.createClass` gives a deprecation warning as of [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass) and will be removed in v16.
It appears there are[ two solutions](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass). ES6 Classes or the `create-react-class` module. I  put in a PR #19 using ES6.

**Comment by maikthomas** [comment]
@chenglou

**Comment by chenglou** [comment]
Thanks! Merged and published. If that didn't work, please ping me =)
